# Generated by Django 4.1.4 on 2025-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('min_state_salary', models.FloatField()),
                ('max_state_salary', models.FloatField()),
                ('pace', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
    ]
