# Generated by Django 4.2.18 on 2025-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateSalary',
        ),
    ]
