# Generated by Django 4.2.18 on 2025-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('similar', models.CharField(max_length=100)),
            ],
        ),
    ]
