# Generated by Django 4.2.18 on 2025-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries_app', '0002_similaritypair'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistogramCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
